In [23]:
import urllib.request
from lxml import etree
from urllib import parse
import sqlite3

In [67]:
conn=sqlite3.connect("air.db")
conn.execute("DROP table airDB;")
conn.execute('''
CREATE TABLE airDB(
    sidoName TEXT,
    dataTime TEXT,
    mangName TEXT,
    so2Value REAL,
    coValue REAL,
    o3Value REAL,
    no2Value REAL,
    pm10Value REAL,
    pm10Value24 REAL,
    pm25Value REAL,
    pm25Value24 REAL,
    khaiValue REAL,
    khaiGrade INT,
    so2Grade INT,
    coGrade INT,
    o3Grade INT,
    no2Grade INT,
    pm10Grade INT,
    pm25Grade INT,
    pm10Grade1h INT,
    pm25Grade1h INT,
    PRIMARY KEY (sidoName, dataTime)

);
''')
print("success")

success

In [60]:
sql="insert or replace into airDB (sidoName, dataTime, mangName, so2Value, coValue, o3Value, no2Value, pm10Value, pm10Value24,pm25Value, pm25Value24, khaiValue, khaiGrade, so2Grade, coGrade, o3Grade, no2Grade, pm10Grade, pm25Grade, pm10Grade1h, pm25Grade1h) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)"

In [68]:
def getAirContent(url,params):
    sidoName=params["stationName"]
    params["serviceKey"]=urllib.parse.unquote(params["serviceKey"])
    params = urllib.parse.urlencode(params)
    params =params.encode("utf-8")
    #print(params)
    req=urllib.request.Request(url,data=params)
    res=urllib.request.urlopen(req)
    resResult=res.read()
    xml=etree.fromstring(resResult)
    xmlTree=etree.ElementTree(xml)
    root=xmlTree.getroot()
    items=root.findall(".//item")
    for item in items:
  #      print(item.text)#item당 20개의 요소들이 들어있음
        for i in range(0,20):
            print(item[i].text)#태그(키)와 value들
        conn.execute(sql, (sidoName,item[0].text, item[1].text, item[2].text, item[3].text, item[4].text, item[5].text, item[6].text, item[7].text, item[8].text, item[9].text, item[10].text, item[11].text, item[12].text, item[13].text, item[14].text, item[15].text, item[16].text, item[17].text, item[18].text, item[19].text))
        conn.commit()

In [78]:
url="http://openapi.airkorea.or.kr/openapi/services/rest/ArpltnInforInqireSvc/getMsrstnAcctoRltmMesureDnsty"
params={"serviceKey":"vMczsU44uukLKVuQWTXfD5kbAmvI0%2BeNQskR5BBR6r6qgoos6%2FJYLPa5pVhMyRokRDIh5kka%2F58NNDxsEhjj%2Fw%3D%3D",
        "numOfRows":10,
        "pageNo":1,
        "stationName":"송파구",
        "dataTerm":"DAILY",
        "ver":"1.3",
}
getAirContent(url,params)

2018-07-17 24:00
도시대기
0.005
0.5
0.003
0.022
28
32
24
23
69
2
1
1
1
1
2
2
1
2
2018-07-17 23:00
도시대기
0.004
0.5
0.003
0.023
32
33
22
23
69
2
1
1
1
1
2
2
2
2
2018-07-17 22:00
도시대기
0.003
0.5
0.003
0.026
31
32
20
23
69
2
1
1
1
1
2
2
2
2
2018-07-17 21:00
도시대기
0.002
0.5
0.005
0.024
25
33
13
24
72
2
1
1
1
1
2
2
1
1
2018-07-17 20:00
도시대기
0.003
0.4
0.008
0.025
30
36
22
26
77
2
1
1
1
1
2
2
1
2
2018-07-17 19:00
도시대기
0.003
0.5
0.015
0.020
31
38
25
26
77
2
1
1
1
1
2
2
2
2
2018-07-17 18:00
도시대기
0.003
0.4
0.021
0.019
36
39
31
25
74
2
1
1
1
1
2
2
2
2
2018-07-17 17:00
도시대기
0.003
0.4
0.030
0.018
42
-
33
-
-
None
1
1
1
1
None
None
2
2
2018-07-17 16:00
도시대기
0.004
0.5
0.038
0.020
52
-
35
-
-
None
1
1
2
1
None
None
2
2
2018-07-17 15:00
도시대기
-
-
-
-
-
-
-
-
-
None
None
None
None
None
None
None
None
None

In [80]:
conn.close()